// <auto-generated/>
#ifndef _VERSION_FILE_H_
#define _VERSION_FILE_H_

#define szVerMajorMinor "3.11"
#define szVerMajorMinorBuild "3.11.1"
#define szVerMajorMinorBuildRev "3.11.1.2318"
#define rmj	3
#define rmm	11
#define rup	1
#define rev	2318
#define szVerName	"BalExtension Release"

#endif
